version: 0.0
os: linux

files:
  - source: /flow-back
    destination: /home/ubuntu/project
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  ApplicationStart:
    - location: /flow-back/scripts/deploy.sh
      timeout: 600
      runas: root