spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true


front-server: http://ec2-43-201-50-199.ap-northeast-2.compute.amazonaws.com:3000